CREATE OR REPLACE VIEW
	collectionTwo_collecting_event AS
	SELECT
		v.`intSiteVisitID`,
		v.`vchrSiteVisitName`,
		v.`vchrFieldNumber`,
		v.`vchrCollector`,
		v.`tintDateType`,
		v.`intDateStart`,
		v.`intDateEnd`,
		v.`intTimeStart`,
		v.`intTimeEnd`,
		v.`vchrCasualTime`,
		v.`dtDateCreated`      AS siteVisitdtDateCreated,
		v.`vchrWhoCreated`     AS siteVisitvchrWhoCreated,
		v.`dtDateLastUpdated`  AS siteVisitdtDateLastUpdated,
		v.`vchrWhoLastUpdated` AS siteVisitvchrWhoLastUpdated,
		v.`tintTemplate`       AS siteVisitTintTemplate,
		v.`GUID`               AS siteVisitGUID,
		s.`intSiteID`,
		s.`vchrSiteName`,
		s.`intPoliticalRegionID`,
		s.`intSiteGroupID`,
		s.`tintLocalType`,
		s.`vchrLocal`,
		s.`vchrDistanceFromPlace`,
		s.`vchrDirFromPlace`,
		s.`vchrInformalLocal`,
		s.`tintPosCoordinates`,
		s.`tintPosAreaType`,
		s.`fltPosY1`,
		s.`fltPosX1`,
		s.`fltPosX2`,
		s.`fltPosY2`,
		s.`tintPosXYDisplayFormat`,
		s.`vchrPosSource`,
		s.`vchrPosError`,
		s.`vchrPosWho`,
		s.`vchrPosDate`,
		s.`vchrPosOriginal`,
		s.`vchrPosUTMSource`,
		s.`vchrPosUTMMapProj`,
		s.`vchrPosUTMMapName`,
		s.`vchrPosUTMMapVer`,
		s.`tintElevType`,
		s.`fltElevUpper`,
		s.`fltElevLower`,
		s.`fltElevDepth`,
		s.`vchrElevUnits`,
		s.`vchrElevSource`,
		s.`vchrElevError`,
		s.`vchrGeoEra`,
		s.`vchrGeoState`,
		s.`vchrGeoPlate`,
		s.`vchrGeoFormation`,
		s.`vchrGeoMember`,
		s.`vchrGeoBed`,
		s.`vchrGeoName`,
		s.`vchrGeoAgeBottom`,
		s.`vchrGeoAgeTop`,
		s.`vchrGeoNotes`,
		s.`dtDateCreated`      AS sitedtDateCreated,
		s.`vchrWhoCreated`     AS sitevchrWhoCreated,
		s.`dtDateLastUpdated`  AS sitedtDateLastUpdated,
		s.`vchrWhoLastUpdated` AS sitevchrWhoLastUpdated,
		s.`intOrder`,
		s.`tintTemplate`       AS siteTintTemplate,
		s.`GUID`               AS siteGUID
	FROM tblSiteVisit v

		JOIN tblSite s ON v.intSiteID = s.intSiteID
	ORDER BY s.intSiteID, v.intSiteVisitID;
