CREATE OR REPLACE VIEW CMS_TEAM_MEMBERSHIP_SORTED_V AS
SELECT *
	FROM CMS_TEAM_MEMBERSHIP_V tm
	ORDER BY tm.LEGACYID_CTM, tm.MEMBERTYPE, tm.TEAMORDER;

CREATE OR REPLACE VIEW CMS_COLLECTING_TEAM_W_MEMBERS_V AS
	SELECT
		t.LEGACYID_CTM,
		t.PRIMARYNAME,
		t.OTHERNAME,
		t.CREATEDBY,
		t.CREATEDATE,
		t.UPDATEDBY,
		t.UPDATEDATE,
		GROUP_CONCAT(IF(tm.MEMBERTYPE = 'P', CONCAT('collectionOne-', tm.LEGACYID_COLL), NULL)) AS primaryMembers,
		GROUP_CONCAT(IF(tm.MEMBERTYPE = 'O', CONCAT('collectionOne-', tm.LEGACYID_COLL), NULL)) AS otherMembers
	FROM
		CMS_COLLECTING_TEAM_V t LEFT JOIN CMS_TEAM_MEMBERSHIP_SORTED_V tm ON t.LEGACYID_CTM = tm.LEGACYID_CTM
	GROUP BY
		t.LEGACYID_CTM,
		t.PRIMARYNAME,
		t.OTHERNAME,
		t.CREATEDBY,
		t.CREATEDATE,
		t.UPDATEDBY,
		t.UPDATEDATE
	ORDER BY t.LEGACYID_CTM;

