CREATE OR REPLACE VIEW CMS_LINKED_IDENTIFIER_W_ID_NO_V AS
	SELECT 
	LI.LEGACYID_CI,
	LI.LEGACYID_CU,
	LI.IDENTIFIERFOR ,
	LI.LINKEDIDENTIFIER,
	LI.LINKEDIDENTIFIERREMARKS,
	LI.LINKEDURI,
	LI.TYPEOFIDENTIFIER,
	LI.CREATEDBY,
	LI.CREATEDATE,
	LI.UPDATEBY,
	LI.UPDATEDATE,
	CONCAT(CI.LABELCOLLECTIONCODE, '-', CI.ACCESSIONNO, '.', CI.SUFFIX) AS CA_IDNO
	FROM CMS_COLLECTION_ITEM_V CI JOIN CMS_LINKED_IDENTIFIER_V LI USING (LEGACYID_CI);
