CREATE OR REPLACE VIEW CMS_ITEM_RELATIONSHIP_W_ITEM_IDNO_V AS
    SELECT
	FCI.CA_IDNO AS CA_IDNO_FROMITEMID,
	TCI.CA_IDNO AS CA_IDNO_TOITEMID,
	IR.ASSOCIATIONDESCRIPTION,
	IR.CREATEDATE,
	IR.CREATEDBY,
	IR.FROMITEMID,
	IR.FROMRELATIONSHIPDESCRIPTION,
	IR.ITEMRELATIONSHIPREMARKS,
	IR.TOITEMID,
	IR.TORELATIONSHIPDESCRIPTION,
	IR.TYPEOFITEMRELATIONSHIP,
	IR.UPDATEBY,
	IR.UPDATEDATE
    FROM 
	CMS_ITEM_RELATIONSHIP_V IR
	LEFT JOIN CMS_COLLECTION_ITEM_W_LABEL_V FCI ON IR.FROMITEMID = FCI.LEGACYID_CI
	LEFT JOIN CMS_COLLECTION_ITEM_W_LABEL_V TCI ON IR.TOITEMID = TCI.LEGACYID_CI;
