CREATE OR REPLACE VIEW collectionOne_event_names AS SELECT `LEGACYID_CE`, GROUP_CONCAT(DISTINCT `RECORDNUMBER`) AS `NAMES`, COUNT(*) as `numRecords` from CMS_COLLECTION_UNIT_V `v`
GROUP BY `LEGACYID_CE`
HAVING `numRecords` <=5
;

CREATE OR REPLACE VIEW CMS_COLLECTING_EVENT_W_CU_NAMES_V AS
	SELECT
		`CE`.`LEGACYID_CE`,
		`LA`.`NAMES` as `TOP_5_CU_NAMES`,
                `CTM`.`PRIMARYNAME`,
		L.LOCALITY,
		`CE`.`VERBATIMDATE`,
		`CE`.`HABITAT`,
		`CE`.`TOPOGRAPHY`,
		`CE`.`ASPECT`,
		`CE`.`SLOPE`,
		`CE`.`GEOLOGICALSUBSTRATE`,
		`CE`.`SOIL`,
		`CE`.`VEGETATION`,
		`CE`.`ASSOCIATED_SPECIES`,
		`CE`.`LEGACYID_CTM`,
		`CE`.`STARTDATE`,
		`CE`.`ENDDATE`,
		`CE`.`FLORAOF`,
		`CE`.`RECORDORIGIN`,
		`CE`.`CREATEDBY`,
		`CE`.`CREATEDATE`,
		`CE`.`UPDATEDBY`,
		`CE`.`UPDATEDDATE`
	FROM `CMS_COLLECTING_EVENT_V` `CE` LEFT JOIN `CMS_LOCATION_V` `L`
		ON `CE`.`LEGACYID_LOCN` = `L`.`LEGACYID_LOCN` LEFT JOIN `CMS_COLLECTING_TEAM_V` `CTM`
		ON `CTM`.`LEGACYID_CTM` = `CE`.`LEGACYID_CTM` LEFT JOIN `collectionOne_event_names` `LA`
		ON `CE`.`LEGACYID_CE` = `LA`.`LEGACYID_CE`

