ALTER DATABASE CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `CMS_COLLECTION_UNIT_V`;
CREATE TABLE `CMS_COLLECTION_UNIT_V`
(
	LEGACYID_CU INT(11) PRIMARY KEY,
	EXCHANGEUNITID INT(11),
	LEGACYID_CE INT(11),
	RECORDNUMBER VARCHAR(40),
	ESTABLISHMENTMEANS VARCHAR(255),
	LIFESTAGE VARCHAR(255),
	LIFEFORM  VARCHAR(255),
	HABIT VARCHAR(1500),
	ORGANISMQUANTITY TEXT,
	ORGANISMQUANTITYTYPE VARCHAR(255),
	ORIGINOFMATERIAL VARCHAR(255),
	CollectionTwoMATERIAL VARCHAR(255),
	GARDENSMATERIAL VARCHAR(255),
	HORTLABELSUFFIX VARCHAR(255),
	ETHNOFLAG VARCHAR(255),
	EXSIC VARCHAR(255),
	EXSICCATAFASCICLE VARCHAR(255),
	EXSICCATANUMBER VARCHAR(255),
	CollectionTwoMATERIALREQUIREDFLAG VARCHAR(255),
	CollectionTwoMATERIALREQDDESCRIPTION VARCHAR(255),
	INTERNALNOTE TEXT,
	OCCURRENCEREMARKS TEXT,
	CREATEDBY VARCHAR(255),
	CREATEDATE DATE,
	UPDATEDBY VARCHAR(255),
	UPDATEDATE DATE
);
ALTER TABLE `CMS_COLLECTION_UNIT_V`
	ADD INDEX (LEGACYID_CE),
	ADD INDEX (RECORDNUMBER);

DROP TABLE IF EXISTS `CMS_TAXON_V`;
CREATE TABLE `CMS_TAXON_V` (
	LEGACYID_TAXON INT(6) PRIMARY KEY,
	LEGACYID_PT INT(6),
	LEGACYID_PT2 INT(7),
	SCIENTIFICNAMEID VARCHAR(255),
	SCIENTIFICNAME VARCHAR(255),
	SIMPLENAME VARCHAR(255),
	SCIENTIFICNAMEAUTHORSHIP VARCHAR(255),
	NAMEPUBLISHEDINYEAR VARCHAR(4),
	LEGACYID_RANK INT(3),
	VERNACULARNAME VARCHAR(255),
	CULTIVARREGISTRATIONTYPE VARCHAR(30),
	CULTIVARGROUPNAME VARCHAR(255),
	CULTIVARNAME VARCHAR(255),
	TRADEDESIGNATION VARCHAR(255),
	HYBRIDFLAG CHAR(2),
	TAXONOMICSTATUS VARCHAR(8),
	NOMENCLATURALSTATUS VARCHAR(15),
	CHANGEDCOMBINATION VARCHAR(255),
	TAXONREMARKS VARCHAR(255),
	TAGNAME VARCHAR(60),
	ACCESSSTATUS VARCHAR(255),
	ACCESSREASON VARCHAR(255),
	CREATEDBY VARCHAR(30),
	CREATEDATE DATE,
	UPDATEDBY VARCHAR(30),
	UPDATEDATE DATE
);
ALTER TABLE `CMS_TAXON_V`
	ADD INDEX (LEGACYID_PT),
	ADD INDEX (LEGACYID_PT2),
	ADD INDEX (LEGACYID_RANK),
	ADD INDEX (SCIENTIFICNAME(160)),
	ADD INDEX (NOMENCLATURALSTATUS(13)),
	ADD INDEX (TAXONOMICSTATUS);

DROP TABLE IF EXISTS `CMS_TAXON_RANK_V`;
CREATE TABLE `CMS_TAXON_RANK_V`(
	LEGACYID_RANK INT(3) PRIMARY KEY,
	NOMENCLATURALCODE CHAR(3),
	TAXONRANK VARCHAR(25),
	TAXONRANKCODE VARCHAR(25),
	TAXONRANKORDER INT(3),
	CREATEDBY VARCHAR(255),
	CREATEDATE VARCHAR(255),
	UPDATEDBY  VARCHAR(255),
	UPDATEDATE VARCHAR(255)
);
ALTER TABLE `CMS_TAXON_RANK_V`
	ADD INDEX (NOMENCLATURALCODE),
	ADD INDEX (TAXONRANK),
	ADD INDEX (TAXONRANKCODE),
	ADD INDEX (TAXONRANKORDER);

DROP TABLE IF EXISTS `CMS_COLLECTOR_V`;
CREATE TABLE `CMS_COLLECTOR_V`(
	LEGACYID_COLL INT(5) PRIMARY KEY,
	DISCIPLINENAME CHAR(4),
	COLLECTORNAME VARCHAR(80),
	CREATEDBY VARCHAR(255),
	CREATEDATE VARCHAR(255),
	UPDATEDBY  VARCHAR(255),
	UPDATEDATE VARCHAR(255)
);
ALTER TABLE `CMS_COLLECTOR_V`
	ADD INDEX (LEGACYID_COLL),
	ADD INDEX (COLLECTORNAME);

DROP TABLE IF EXISTS `CMS_TEAM_MEMBERSHIP_V`;
CREATE TABLE `CMS_TEAM_MEMBERSHIP_V`(
	LEGACYID_TM INT(7) PRIMARY KEY,
	LEGACYID_CTM INT(7),
	LEGACYID_COLL INT(5),
	MEMBERTYPE VARCHAR(1),
	TEAMORDER INT(255),
	CREATEDBY VARCHAR(255),
	CREATEDATE VARCHAR(255),
	UPDATEDBY  VARCHAR(255),
	UPDATEDATE VARCHAR(255)
);
ALTER TABLE `CMS_TEAM_MEMBERSHIP_V`
	ADD INDEX (LEGACYID_TM),
	ADD INDEX (LEGACYID_CTM),
	ADD INDEX (LEGACYID_COLL);

DROP TABLE IF EXISTS `CMS_COLLECTING_TEAM_V`;
CREATE TABLE `CMS_COLLECTING_TEAM_V`(
	LEGACYID_CTM INT(7) PRIMARY KEY,
	PRIMARYNAME VARCHAR(120),
	OTHERNAME VARCHAR(120),
	CREATEDBY VARCHAR(255),
	CREATEDATE VARCHAR(255),
	UPDATEDBY  VARCHAR(255),
	UPDATEDATE VARCHAR(255)
);
ALTER TABLE `CMS_COLLECTING_TEAM_V`
	ADD INDEX (LEGACYID_CTM),
	ADD INDEX (PRIMARYNAME),
	ADD INDEX (OTHERNAME);

DROP TABLE IF EXISTS `CMS_DATASET_V`;
CREATE TABLE `CMS_DATASET_V`(
	DATASET_ID INT PRIMARY KEY,
	DATASET_NAME VARCHAR(100)
);
ALTER TABLE `CMS_DATASET_V`
	ADD INDEX (DATASET_ID);

DROP TABLE IF EXISTS `CMS_LOCATION_V`;
CREATE TABLE `CMS_LOCATION_V`(
	LEGACYID_LOCN INT(7) PRIMARY KEY,
	LEGACYID_RG INT(5),
	LOCALITY VARCHAR(600),
	VERBATIMLOCALITY TEXT,
	VERBATIMCOORDINATESYSTEM VARCHAR(25),
	VERBATIMLATITUDE VARCHAR(125),
	VERBATIMLONGITUDE VARCHAR(125),
	COORDINATESZONE TEXT,
	COORDINATESEASTING TEXT,
	COORDINATESNORTHING TEXT,
	NEARESTNAMEDPLACE VARCHAR(50),
	DISTANCEFROMPLACE TEXT,
	DIRECTIONFROMPLACE TEXT,
	LOCATIONREMARKS VARCHAR(426),
	MUNICIPALITY TEXT,
	LOCATIONID TEXT,
	HIGHERGEOGRAPHYID TEXT,
	HIGHERGEOGRAPHY TEXT,
	CONTINENT TEXT,
	WATERBODY TEXT,
	ISLANDGROUP VARCHAR(50),
	COUNTRY VARCHAR(50),
	STATEPROVINCE VARCHAR(50),
	COUNTY VARCHAR(50),
	CollectionTwoREGION VARCHAR(50),
	BARLOWREGION VARCHAR(50),
	DECIMALLATITUDE FLOAT,
	DECIMALLONGITUDE FLOAT,
	GEODETICDATUM CHAR(5),
	COORDINATEUNCERTAINTYQUANTITY INT,
	COORDINATEUNCERTAINTYUNIT CHAR(6),
	COORDINATEPRECISION INT,
	GEOREFERENCEDBYCODE VARCHAR(32),
	GEOREFERENCESOURCES VARCHAR(20),
	GEOREFERENCEDDATE TEXT,
	GEOREFERENCEVERIFICATIONSTATUS VARCHAR(1),
	GEOREFERENCEREMARKS TEXT,
	VERBATIMELEVATION TEXT,
	ELEVATIONUNIT VARCHAR(6),
	ELEVATIONMINIMUM INT,
	ELEVATIONMAXIMUM INT,
	ELEVATIONBYCODE VARCHAR(255),
	ELEVATIONSOURCES VARCHAR(20),
	ELEVATIONUNCERTAINTY INT(4),
	VERBATIMDEPTH TEXT,
	DEPTHUNIT CHAR(6),
	DEPTHMINIMUM DEC(4,2),
	DEPTHMAXIMUM DEC(4,2),
	DISTANCEABOVESURFACEUNIT TEXT,
	DISTANCEABOVESURFACEMINIMUM TEXT,
	DISTANCEABOVESURFACEMAXIMUM TEXT,
	VERBATIMABOVESURFACE TEXT,
	ACCESSSTATUS TEXT,
	ACCESSREASON TEXT,
	INTERNALNOTE VARCHAR(255),
	CREATEDBY VARCHAR(30),
	CREATEDDATE VARCHAR(255),
	UPDATEDBY VARCHAR(30),
	UPDATEDDATE VARCHAR(255)
);
ALTER TABLE `CMS_LOCATION_V`
	ADD INDEX (LEGACYID_LOCN),
	ADD INDEX (LEGACYID_RG);

DROP TABLE IF EXISTS `CMS_COLLECTING_EVENT_V`;
CREATE TABLE `CMS_COLLECTING_EVENT_V`(
	LEGACYID_CE INT(7) PRIMARY KEY,
	LEGACYID_LOCN INT(7),
	LEGACYID_CTM INT(7),
	DATASETID INT,
	VERBATIMDATE VARCHAR(173),
	STARTDATE VARCHAR(85),
	ENDDATE VARCHAR(85),
	FLORAOF VARCHAR(25),
	TOPOGRAPHY VARCHAR(250),
	ASPECT VARCHAR(3),
	SLOPE INT(2),
	GEOLOGICALSUBSTRATE VARCHAR(80),
	SOIL VARCHAR(80),
	VEGETATION VARCHAR(2000),
	HABITAT VARCHAR(1500),
	ASSOCIATED_SPECIES VARCHAR(250),
	RECORDORIGIN VARCHAR(150),
	EVENTNOTES VARCHAR(219),
	CREATEDBY VARCHAR(30),
	CREATEDATE VARCHAR(255),
	UPDATEDBY VARCHAR(30),
	UPDATEDDATE VARCHAR(255)
);
ALTER TABLE `CMS_COLLECTING_EVENT_V`
	ADD INDEX (LEGACYID_LOCN),
	ADD INDEX (LEGACYID_CTM),
	ADD INDEX (`DATASETID`),
	ADD INDEX (`VERBATIMDATE`),
	ADD INDEX (`STARTDATE`),
	ADD INDEX (`ENDDATE`),
	ADD INDEX (`FLORAOF`),
	ADD INDEX (`TOPOGRAPHY`),
	ADD INDEX (`ASPECT`),
	ADD INDEX (`SLOPE`),
	ADD INDEX (`GEOLOGICALSUBSTRATE`),
	ADD INDEX (`SOIL`),
	ADD INDEX (`ASSOCIATED_SPECIES`),
	ADD INDEX (`RECORDORIGIN`),
	ADD INDEX (`EVENTNOTES`),
	ADD INDEX (`CREATEDBY`),
	ADD INDEX (`CREATEDATE`),
	ADD INDEX (`UPDATEDBY`),
	ADD INDEX (`UPDATEDDATE`);

DROP TABLE IF EXISTS `CMS_IDENTIFICATION_V`;
CREATE TABLE `CMS_IDENTIFICATION_V`(
	LEGACYID_IDENT INT(8) PRIMARY KEY,
	LEGACYID_TAXON INT(6),
	LEGACYID_CU INT(7),
	VERBATIMDATEIDENTIFIED VARCHAR(32),
	DATEIDENTIFIED VARCHAR(255),
	CURRENTDETFLAG CHAR(1),
	IDENTIFIEDBY VARCHAR(60),
	TAGNAME VARCHAR(0),
	AUTHORISEDBY VARCHAR(0),
	IDENTIFICATIONREFERENCES VARCHAR(0),
	IDENTIFICATIONREMARKS VARCHAR(255),
	INTERNALNOTE  VARCHAR(512),
	IDENTIFIERROLE  VARCHAR(5),
	IDENTIFICATIONQUALIFIER  VARCHAR(10),
	NAMEADDENDUM CHAR(7),
	IDENTIFICATIONMETHOD VARCHAR(0),
	REFERENCEPAGE VARCHAR(0),
	IDENTIFICATIONREFERENCECODE VARCHAR(0),
	IDENTIFICATIONVERIFYSTATUS VARCHAR(0),
	IDENTIFICATIONSEQUENCE INT(2),
	CREATEDBY VARCHAR(30),
	CREATEDATE VARCHAR(255),
	UPDATEDBY VARCHAR(30),
	UPDATEDATE VARCHAR(255)
);
ALTER TABLE `CMS_IDENTIFICATION_V`
	ADD INDEX(LEGACYID_IDENT),
	ADD INDEX(LEGACYID_TAXON),
	ADD INDEX(LEGACYID_CU)
;

DROP TABLE IF EXISTS `CMS_IDENTIFICATION_V`;
CREATE TABLE `CMS_IDENTIFICATION_V`(
	LEGACYID_IDENT INT(8) PRIMARY KEY,
	LEGACYID_TAXON INT(6),
	LEGACYID_CU INT(7),
	VERBATIMDATEIDENTIFIED VARCHAR(32),
	DATEIDENTIFIED VARCHAR(255),
	CURRENTDETFLAG CHAR(1),
	IDENTIFIEDBY VARCHAR(60),
	TAGNAME VARCHAR(0),
	AUTHORISEDBY VARCHAR(0),
	IDENTIFICATIONREFERENCES VARCHAR(0),
	IDENTIFICATIONREMARKS VARCHAR(255),
	INTERNALNOTE  VARCHAR(255),
	IDENTIFIERROLE  VARCHAR(5),
	IDENTIFICATIONQUALIFIER  VARCHAR(10),
	NAMEADDENDUM CHAR(7),
	IDENTIFICATIONMETHOD VARCHAR(0),
	REFERENCEPAGE VARCHAR(0),
	IDENTIFICATIONREFERENCECODE VARCHAR(0),
	IDENTIFICATIONVERIFYSTATUS VARCHAR(0),
	IDENTIFICATIONSEQUENCE INT(2),
	CREATEDBY VARCHAR(30),
	CREATEDATE VARCHAR(255),
	UPDATEDBY VARCHAR(30),
	UPDATEDATE VARCHAR(255)
);
ALTER TABLE `CMS_IDENTIFICATION_V`
	ADD INDEX(LEGACYID_IDENT),
	ADD INDEX(LEGACYID_TAXON),
	ADD INDEX(LEGACYID_CU)
;

DROP TABLE IF EXISTS `CMS_COLLECTION_ITEM_V`;
CREATE TABLE `CMS_COLLECTION_ITEM_V`(
	LEGACYID_CI INT(8) PRIMARY KEY,
	LEGACYID_CU INT(7),
	LABELCOLLECTIONCODE VARCHAR(10),
	ACCESSIONNO VARCHAR(15),
	SUFFIX INT(3),
	ITEMTYPE VARCHAR(30),
	CURRENTSTATUS CHAR(1),
	CURRENTSTATUSQUALIFIER TEXT,
	`CONDITION` TEXT,
	COUNT TEXT,
	COUNTQUALIFIER TEXT,
	SEX TEXT,
	LIFESTAGE CHAR(8),
	LIFEFORM TEXT,
	ORIGINOFRECORD VARCHAR(140),
	BASISOFRECORD CHAR(17),
	DCTERMSTYPE VARCHAR(14),
	ACCESSSTATUS TEXT,
	ACCESSREASON TEXT,
	ACCESSIONDATE DATETIME ,
	DEACCESSIONDATE DATETIME,
	INTERNALNOTE TEXT,
	ITEMREMARKS TEXT,
	INTERNALCATALOGNUMBER TEXT,
	RECORDSTATUS CHAR(9),
	CREATEDBY VARCHAR(30),
	CREATEDATE VARCHAR(255),
	UPDATEDBY VARCHAR(30),
	UPDATEDATE VARCHAR(255)
);
ALTER TABLE `CMS_COLLECTION_ITEM_V`
	ADD INDEX(LEGACYID_CI),
	ADD INDEX(LEGACYID_CU),
	ADD INDEX(LABELCOLLECTIONCODE),
	ADD INDEX(ITEMTYPE),
	ADD INDEX(CURRENTSTATUS),
	ADD INDEX(DCTERMSTYPE)
;

DROP TABLE IF EXISTS `CMS_LINKED_IDENTIFIER_V`;
CREATE TABLE `CMS_LINKED_IDENTIFIER_V`(
	LEGACYID_CI INT,
	LEGACYID_CU INT(7),
	IDENTIFIERFOR VARCHAR(100),
	LINKEDIDENTIFIER VARCHAR(92),
	LINKEDIDENTIFIERREMARKS VARCHAR(240),
	LINKEDURI INT,
	TYPEOFIDENTIFIER VARCHAR(8),
	CREATEDBY VARCHAR(30),
	CREATEDATE VARCHAR(255),
	UPDATEBY VARCHAR(30),
	UPDATEDATE VARCHAR(255)
);
ALTER TABLE `CMS_LINKED_IDENTIFIER_V`
	ADD INDEX(LEGACYID_CI),
	ADD INDEX(LEGACYID_CU)
;

DROP TABLE IF EXISTS `CMS_ITEM_IDENTIFICATION_V`;
CREATE TABLE `CMS_ITEM_IDENTIFICATION_V`(
	LEGACYID_IDENT INT(8),
	LEGACYID_CIIDENT INT(8),
	LEGACYID_CI INT(8),
	TYPEOFTYPE VARCHAR(20),
	TYPEQUALIFIER VARCHAR(10),
	TYPESTATUS TEXT,
	CREATEDBY VARCHAR(30),
	CREATEDATE VARCHAR(255),
	UPDATEDBY VARCHAR(30),
	UPDATEDATE VARCHAR(255)
);
ALTER TABLE `CMS_ITEM_IDENTIFICATION_V`
	ADD INDEX(LEGACYID_CI),
	ADD INDEX(LEGACYID_CIIDENT),
	ADD INDEX(LEGACYID_IDENT)
;


DROP TABLE IF EXISTS `CMS_STORAGE_LOCATION_ALL_V`;
CREATE TABLE `CMS_STORAGE_LOCATION_ALL_V`(
	LEGACYID_SIT INT(8) PRIMARY KEY,
	SIT_MANAGER_ID INT(8),
	SIT_PARENT_ID INT(8),
	SIT_REPORTING_GROUP VARCHAR(30),
	SIT_SORT_ORDER INT(4),
	COMMENTS VARCHAR(240),
	CURRENT_FLAG VARCHAR(1),
	DISCIPLINENAME VARCHAR(4),
	INSTITUTIONCODE VARCHAR(10),
	PUBLIC_ACCESS VARCHAR(1),
	SOURCEID VARCHAR(4),
	STORAGELOCATIONCODE VARCHAR(10),
	STORAGELOCATIONNAME VARCHAR(180),
	STORAGELOCATIONTYPE VARCHAR(30),
	THEME_DESCRIPTION VARCHAR(1024),
	THEME_LIST VARCHAR(100),
	CREATEDBY VARCHAR(30),
	CREATEDATE VARCHAR(255),
	UPDATEDBY VARCHAR(30),
	UPDATEDATE VARCHAR(255)
);
ALTER TABLE `CMS_STORAGE_LOCATION_ALL_V`
	ADD INDEX(SIT_MANAGER_ID),
	ADD INDEX(SIT_PARENT_ID)
;

DROP TABLE IF EXISTS `CMS_ITEM_STORAGE_LOCATION_V`;
CREATE TABLE `CMS_ITEM_STORAGE_LOCATION_V`(
	LEGACYID_ISIT INT(8) PRIMARY KEY,
	LEGACYID_CI INT(8),
	LEGACYID_SIT INT(8),
	ENDDATE DATE,
	STARTDATE DATE,
	INTERNALNOTE VARCHAR(44),
	CREATEDBY VARCHAR(30),
	CREATEDATE VARCHAR(255),
	UPDATEDBY VARCHAR(30),
	UPDATEDATE VARCHAR(255)
);
ALTER TABLE `CMS_ITEM_STORAGE_LOCATION_V`
	ADD INDEX(LEGACYID_CI),
	ADD INDEX(LEGACYID_SIT)
;

DROP TABLE IF EXISTS `CMS_ITEM_PREPARATION_TYPE_V`;
CREATE TABLE `CMS_ITEM_PREPARATION_TYPE_V`(
	LEGACYID_CI INT(8),
	PREPARATIONTYPE VARCHAR(11),
	CREATEDBY VARCHAR(30),
	CREATEDATE VARCHAR(255),
	UPDATEDBY VARCHAR(30),
	UPDATEDATE VARCHAR(255)
);
ALTER TABLE `CMS_ITEM_PREPARATION_TYPE_V`
	ADD INDEX(LEGACYID_CI)
;

DROP TABLE IF EXISTS `CMS_ITEM_RELATIONSHIP_V`;
CREATE TABLE `CMS_ITEM_RELATIONSHIP_V`(
	TOITEMID INT(8),
	FROMITEMID INT(8),
	ASSOCIATIONDESCRIPTION VARCHAR(14),
	FROMRELATIONSHIPDESCRIPTION VARCHAR(8),
	ITEMRELATIONSHIPREMARKS TEXT,
	TORELATIONSHIPDESCRIPTION VARCHAR(9),
	TYPEOFITEMRELATIONSHIP VARCHAR(20),
	CREATEDBY VARCHAR(30),
	CREATEDATE VARCHAR(255),
	UPDATEBY VARCHAR(30),
	UPDATEDATE VARCHAR(255)
);
ALTER TABLE `CMS_ITEM_RELATIONSHIP_V`
	ADD INDEX(TOITEMID),
	ADD INDEX(FROMITEMID)
;

DROP TABLE IF EXISTS `CMS_ITEM_PART_V`;
CREATE TABLE `CMS_ITEM_PART_V`(
	LEGACYID_CI INT(8),
	PARTTYPE VARCHAR(255),
	CREATEDBY VARCHAR(30),
	CREATEDATE VARCHAR(255),
	UPDATEDBY VARCHAR(30),
	UPDATEDATE VARCHAR(255)
);
ALTER TABLE `CMS_ITEM_PART_V`
	ADD INDEX(LEGACYID_CI),
	ADD INDEX(PARTTYPE)
;